# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='amount',
            new_name='amount_left',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='code',
            new_name='barcode',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='retail_price',
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='vendor_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
